os: Visual Studio 2017
configuration: Release
platform: Any CPU
version: '3.0.{build}'

build:
  project: source\Packsly3.sln
  verbosity: minimal
  
branches:
  except:
    - /depreciated\\.*/
    - /test\\.*/

before_build:
  cmd: nuget restore source\Packsly3.sln

assembly_info:
  patch: true
  file: source\modules\Packsly3.Cli\Properties\AssemblyInfo.cs
  assembly_version: '{version}'

artifacts:
  path: source\modules\Packsly3.Cli\bin\Release
  name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION)
  type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: wzztgAMUTfmbyw7/xz9gB5X8L4QvW8Mzaq006r8RmTS5YnbZ7VUvNtH4MTcc4s0O
  release: $(APPVEYOR_PROJECT_NAME) $(APPVEYOR_BUILD_VERSION)
  tag: $(APPVEYOR_BUILD_VERSION)
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true